### PR TITLE
Gwcs refactor

### PR DESCRIPTION
**Pull request by nmearl**
This PR removes the adapter classes from specutils and relies on the unified WCS API implemented in both fitswcs and gwcs.
A few problems remain:
- [x] This requires that the transformations in gwcs be unit-aware (spacetelescope/gwcs#210)
- [x] Requires a fix for the return arrays of fitswcs transformations (astropy/astropy#8559)

### CODE REVIEW

**Comment by hamogu** [comment]
This overlaps with #407. I was going to implement the simple change suggested there now, but if you want to work that into this PR instead let me know.

**Comment by javerbukh** [comment]
@nmearl it seems this PR was abandoned in favor of #407, should this remain open?

**Comment by nmearl** [comment]
@javerbukh PR #407 is not related to this.

Changes to PR now include @nden's PR #490 and requires that GWCS merged PR spacetelescope/gwcs#261. 

This PR now fully address #553 by completely removing the wcs adapter infrastructure, relying solely on APE14, and refactoring model behavior with the changes in astropy 4.0.

**Comment by eteq** [comment]
The remaining failures are either network problem (a single test is failing on all of them due to that) or the thing that will be fixed in #564 .  So this is good to go!

**Pull request merged**
