### PR TITLE
Several changes to handle standard FITS spectra files

### PR DESCRIPTION
**Pull request by profxj**
1.  Added DC-FLAG handling
2.  Dealt with BZERO (maybe not quite right..)
3.  Added error file to read_fits.read_fits_spectrum1d

### CODE REVIEW

**Comment by profxj** [comment]
Ok, I decided to slow down and learn more Python/git 
before digging back in.

Have just made a PR (#111) for the Log changes.  
In the end, I decided to only modify Spectrum1DPolynomialWCS
in the WCS entries.  I suspect this is the only one that would
use this functionality.

Will proceed more slowly with specutils going forward.

Cheers,

X


----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/profxj/xastropy

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by wkerzendorf** [comment]
Hi Xavier,

No problem at all. First of all: Happy new year!! I'll have a look at the
new PR. Shailesh implemented the log WCS for one of the WCS encodings. I
think it might be useful to use the same machinery for the DC-FLAG. One
other problem I encountered and never quite knew how to solve is when
conflicting keywords are present.


Cheers,
   Wolfgang

**Comment by wkerzendorf** [comment]
@profxj can we close this PR?

**Comment by profxj** [comment]
Yes, close the #108 PR.

X

On Jan 3, 2015, at 4:12 AM, Wolfgang Kerzendorf <notifications@github.com> wrote:

> @profxj can we close this PR?
> 
> —
> Reply to this email directly or view it on GitHub.
> 
> !DSPAM:826,54a7e02615332272577083!

----------------------------------------------
J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/profxj/xastropy

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Pull request closed without merging**
