### PR TITLE
Update test envs now that python 3.12 is released

### PR DESCRIPTION
**Pull request by rosteen**
Updates our OS tests to all use python 3.12 and adds a test to keep checking against 3.11.

### CODE REVIEW

**Review by pllim — COMMENTED** [review]
Hmm, don't you need quotes around python for python>=3.10 ?

```yaml
python: '3.11'
```

**Comment by rosteen** [comment]
> Hmm, don't you need quotes around python for python>=3.10 ?

I thought the problem was specific to 3.10, since parsing that as a float would make it 3.1, whereas 3.11 would keep the full value.

**Comment by pllim** [comment]
oldest deps failure is caused by #1091

devdeps failure is caused by something preventing scipy from upgrading to dev version: `numpy==2.0.0.dev0` vs `scipy==1.11.3` (while we're at it, looks like matplotlib also failed to upgrade, which is very annoying)

**Comment by pllim** [comment]
I fixed oldest-deps, so you should rebase if you still want to pursue this.

**Pull request closed without merging**
