### PR TITLE
Keep model names after fitting

### LINKED ISSUE #503: Model subcomponents names are not preserved after fitting
I noticed that the *QuantityModel* output of the method *fit_lines* does not preserved the submodel component names, making it difficult to retrieve the individual subcomponents after fitting. Is this the expected behaviour?
`line_model_init = models.Gaussian1D(name="comp1") + models.Gaussian1D(name="comp2")
line_model_init.submodel_names`
**('comp1', 'comp2')**
`model_fit = fit_lines(line_spec, line_model_init, fitter=fitter)
model_fit.submodel_names`
**('None_0', 'None_1')**

I cannot access them by doing 
`model_fit.unitless_model["comp1"]` anymore

### PR DESCRIPTION
**Pull request by xuanxu**
This PR makes `fit_lines` to preserve the names of the original model(s) after fitting.

Fixes #503

### CODE REVIEW

**Comment by nmearl** [comment]
Thanks @xuanxu! Can you please include a test (or extend an existing one) that checks that the names within compound models are also maintained (as shown in #503)?

**Comment by xuanxu** [comment]
@nmearl the PR already includes tests:
 - for when there's a name: https://github.com/astropy/specutils/pull/526/files#diff-7fc9812436fbe451ddab32a963e73729R464-R471
 - and for the case of models with empty name: https://github.com/astropy/specutils/pull/526/files#diff-7fc9812436fbe451ddab32a963e73729R479

**Comment by nmearl** [comment]
@xuanxu Those tests only pertain to a single model, not compound models as in the example in the issue.

**Comment by xuanxu** [comment]
@nmearl done! Compound models are covered now.

**Pull request merged**
