### PR TITLE
added functions to Spectrum1D that allow for multiplication, addition…  

### PR DESCRIPTION
**Pull request by ChrisSWDavis**
… and subtraction from the left as well as from the right.

This makes the manipulation of spectra through various operations slightly more flexible and easier for users, so they don't have to add/subtract/multiply floats and ints etc from the right every time.

### CODE REVIEW

**Comment by rosteen** [comment]
Could you give an example of something that uses `__rsub__`, `__rmul__` or `__radd__`? I admit to not really understanding what capability this is adding.

**Comment by rosteen** [comment]
Alright, I answered my own question - I didn't even realize we were missing this capability, thanks for the contribution! I'll add a test or two and then get this in.

**Comment by ChrisSWDavis** [comment]
Hi, apologies for not responding sooner, I got quite busy over the last couple of days. Yeah the changes let you do things like

`float_number + Spectrum_1D_instance `

instead of having to do

`Spectrum_1D_instance + float_number`

every time (where Spectrum_1D_instance is of type Spectrum1D, and float_number is a float).

**Comment by rosteen** [comment]
Sorry for the delay, testing this lead me down a rabbit hole of something that I think will require an upstream fix in `astropy`. I added a changelog entry and tests, I think this is good to go. Thanks again for the contribution.

**Review by rosteen — APPROVED** [review]

**Pull request merged**
