### PR TITLE
Remove unit and spectral_axis_unit from initializer

### PR DESCRIPTION
**Pull request by nmearl**
This PR removes unnecessary keywords from the `Spectrum1D` initializer as discussed in #264.

### CODE REVIEW

**Comment by eteq** [comment]
Tests failed due to the doctests failing. Turns out there were some corrections needed there due to this PR anyway...

**Comment by nmearl** [comment]
I cannot figure out why [this is failing](https://travis-ci.org/astropy/specutils/jobs/427365884#L1283). In previous iterations, it was failing because travis could not import matplotlib for the plotting directives in the docs. I added matplotlib as a dependency in the travis yaml file, but still erroring...

**Comment by eteq** [comment]
Aha, I know at least why the error is only happening in those two cases: #310 added those tests partly because they address a bug fixed in astropy master that prevents the `.rst` files from being run as doctests.  So those two builds are the ones where the doctests get run, and this error comes from running the doctests (i.e. `getting_started.rst`).

The error *itself* is still mysterious to me though - I can't reproduce it locally even if I do `python setup.py test -t docs/getting_started.rst` (which does indeed run the part that's erroring on Travis)

**Comment by eteq** [comment]
Oh, I think I figured it out: matplotlib is trying to pop up a window on travis, which fails because travis runs "headless" (unlike my local testing machine).  A work-around is to just force matplotlib into "agg" mode.  The commit I just pushed up *should* do just that (although we shall see if the tests actually pass...)

**Comment by nmearl** [comment]
@eteq Looks like your changes were the solution. 👍

**Comment by eteq** [comment]
Awesome, LGTM so merging!

**Pull request merged**
