### PR TITLE
Conserve shape of arrays when interpolating

### PR DESCRIPTION
**Pull request by ibusko**
See #760

### CODE REVIEW

**Review by javerbukh — APPROVED** [review]
This looks good and passes all tests locally, although this is another situation where I think a science review is appropriate.

**Review by rosteen — COMMENTED** [review]
Shouldn't this also update the spectral_axis values in the output spectrum? Currently, using the linear interpolation case from the tests (interpolating to spectral axis locations [3.5, 4.7, 6.8, 7.1] * u.AA), the interpolation changes the spectrum from:

`<Spectrum1D(flux=<Quantity [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.] mJy>, spectral_axis=<SpectralAxis [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.] Angstrom>, uncertainty=StdDevUncertainty([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ]))>`

to 

`<Spectrum1D(flux=<Quantity [ 1. ,  2. ,  3. ,  3.5,  4.7,  6.8,  7.1,  8. ,  9. , 10. ] mJy>, spectral_axis=<SpectralAxis [ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.] Angstrom>, uncertainty=StdDevUncertainty([0.1 , 0.2 , 0.3 , 0.35, 0.47, 0.68, 0.71, 0.8 , 0.9 ,
                   1.  ]))>`

As you can see, the output spectrum now contains the flux values appropriate for the desired wavelength values, but the spectral axis still assigns those flux values to the original locations on the spectral axis.

**Comment by ibusko** [comment]
@rosteen you're right. The spectral axis is not being updated. I will push a commit shortly to fix this.

**Review by rosteen — APPROVED** [review]
Looks good to me now after that fix, I don't see anything else that stands out.

**Comment by PatrickOgle** [comment]
I don't completely understand the science use case, even after reading the jdat notebook.  Is the idea to:
1) replace a segment of a spectrum with a spline fit to that segment?
Or to
2) Do (1) and set the spectrum to zero outside of that segment.

The name of the PR "Conserve shape of arrays"  doesn't really get at the intent here.

**Comment by ibusko** [comment]
I understood from the notebook case that the goal is to replace a segment of the spectrum with a fit, and keep the rest of the spectrum as is.

Sent from my iPhone

On Jan 29, 2021, at 11:08, Patrick Ogle <notifications@github.com> wrote:

﻿

I don't completely understand the science use case, even after reading the jdat notebook. Is the idea to:

  1.  replace a segment of a spectrum with a spline fit to that segment?
Or to
  2.  Do (1) and set the spectrum to zero outside of that segment.

The name of the PR "Conserve shape of arrays" doesn't really get at the intent here.

**Comment by eteq** [comment]
I'm fine with this PR as it stands per se, *but* I'm also with @PatrickOgle that I don't understand which developer note this is addressing from #760. Can you clarify which note it is @ibusko ? (even just copy the text here is fine)

**Comment by ibusko** [comment]
This is the developer note: 

"Developer note By fitting a spline to a sub region the spectral shapes are no longer the same. bbsub_spectra.flux.value - spline_spec.flux.value now brakes. Would need to trim the spectrum to the spline size to start looking closely for low contrast dust features and again measure their properties (see above). Some wrapper to stop repeating the same steps over and over would be nice"

**Comment by eteq** [comment]
Hmm. I admit this is a bit ambiguous: I read this as asking for a wrapper that does the *other half* of this: i.e., a desire to trim the spectrum.

**Comment by eteq** [comment]
Oh wait!  Right after sending that last comment I realized that you'd still need what's in this PR to do that.  Am I interpreting that right, @ibusko, that this PR is implementing "step 1", and then we might consider a wrapper that does this *in addition* to trimming to satisfy the developer note as posed?

(If so, then I think this is all set to go in if @PatrickOgle agrees, just doesn't completely address the developer note)

**Comment by PatrickOgle** [comment]
It would make more sense to me to trim the input spectrum to the size of the spline-fitting region then subtract
the spline. However, I don't object to having this functionality as a 'keep shape' option to resample.py.

**Comment by ibusko** [comment]
To conserve the shape of the spline (or other interpolator), we have to do nothing, because this is what the interpolators do that by default.

**Comment by ibusko** [comment]
Yes, it sounds ambiguous. I had interpreted that the function should return only one spectrum instance, as the interpolators currently do. The reverse of what I implemented means that it has to return both the output of the interpolator, as a well as a trimmed version of the input spectrum. Is that what is meant by a 'wrapper'?

**Comment by rosteen** [comment]
For the record, I interpreted the developer note the same way as Ivo: the user was annoyed that they couldn't simply do `bbsub_spectra.flux.value - spline_spec.flux.value` after creating spline_spec, since it was a different size than the original spectrum, and didn't want to have to go through the step of pulling a chunk out of the original spectrum to subtract the spline. However, I agree that it's ambiguous how they actually wanted the problem solved. 

It doesn't seem like it would be too hard (in a follow up) to allow subtracting a smaller spectrum from a larger one (leaving the mismatched regions unaffected) if we end up wanting to go that direction.

**Comment by PatrickOgle** [comment]
I don't think this _keep_shape functionality should be in resample.py.  If we resample the spectrum but keep the same number of wavelength points, the wavelengths will not match up with the original spectrum.   

Also, I don't think this answers the science question of replacing a segment of the spectrum with a spline fit, and that should go somewhere else, not in resample.py. 

I suggest deprecating this PR.

**Pull request closed without merging**
