### PR TITLE
Improve spectra arithmetic

### LINKED ISSUE #989: arithmetic operations don't check compatibility of spectral_axis
Arithmetic operations succeed so long as the flux arrays are of compatible shape, but do not check for equivalent spectral axis values.  For example,

```
from specutils import Spectrum1D
import numpy as np
from astropy import units as u

sp1 = Spectrum1D(np.random.random(10)*u.Jy, spectral_axis=np.linspace(0,1,10)*u.pix)
sp2 = Spectrum1D(np.random.random(10)*u.Jy, spectral_axis=np.linspace(2,8,10)*u.pix)
sp2 - sp1
```
succeeds but returns a `Spectrum1D` object with a spectral axis adopted directly from `sp2`.  Instead this should raise an error (or perhaps eventually support optional interpolation for cases in which there is sufficient overlap).

Related: #198

### PR DESCRIPTION
**Pull request by pllim**
Fix #989 and more.

[🐱](https://jira.stsci.edu/browse/JDAT-2928)

### TODO

- [ ] Rebase
- [ ] Consider implication of https://github.com/astropy/astropy/pull/13977

### CODE REVIEW

**Comment by pllim** [comment]
I don't think the remote data failure is related. It has something to do with this file that I didn't touch.

https://data.sdss.org/sas/dr8/sdss/spectro/redux/26/0273/spPlate-0273-51957.fits

**Comment by pllim** [comment]
If we ever come back to this, need to also consider the implication of https://github.com/astropy/astropy/pull/13977

**Comment by pllim** [comment]
Is there still interest to pursue this or should I just close it without merge?

**Comment by rosteen** [comment]
Yes, there's still interest, but I milestoned it to 2.0 so I haven't been in a rush to get it in.

**Pull request closed without merging**
