### PR TITLE
Add changelog check to CI

### LINKED ISSUE #1165: Do you want a change log bot?
So it can boss Ricky around. 😸 

Bot from https://github.com/scientific-python/action-check-changelogfile

Example usage in https://github.com/astropy/astroquery/blob/main/.github/workflows/changelog.yml

### PR DESCRIPTION
**Pull request by rosteen**
Closes #1165 . Thanks @pllim for the links 🙂

### CODE REVIEW

**Comment by pllim** [comment]
Don't want to use towncrier while you are at it? 😉 

Looks like it works because it is failing because you didn't apply the label. ;D

**Comment by pllim** [comment]
You might have to clean up the change log or something? See warnings in https://github.com/astropy/specutils/actions/runs/11169575830/job/31050585269?pr=1177

Also, from now on, you would need to also make sure all PRs are milestoned properly to match the change log section.

**Comment by rosteen** [comment]
> [](https://github.com/astropy/specutils/actions/runs/11169575830/job/31050585269?pr=1177)
> 
> Also, from now on, you would need to also make sure all PRs are milestoned properly to match the change log section.

Doesn't `CHECK_MILESTONE: false` avoid that check?

**Comment by pllim** [comment]
Oh yeah, maybe. @bsipocz added that one, I think.

**Comment by rosteen** [comment]
Everything in the changelog is passing now except for this PR missing an entry.

**Review by pllim — APPROVED** [review]
It is funny how the bot is even more strict than me. LGTM and looks like https://github.com/astropy/astroquery/blob/main/.github/workflows/changelog.yml . Thanks!

**Comment by pllim** [comment]
I also have a milestone check if you change your mind about milestones. 😆

**Comment by pllim** [comment]
Just gonna leave this here. 😝 

https://github.com/astropy/astropy/blob/main/.github/workflows/check_milestone.yml

**Comment by rosteen** [comment]
Thanks for the help/eyes on this!

**Comment by bsipocz** [comment]
> Oh yeah, maybe. @bsipocz added that one, I think.

You got me in a cold sweat for a moment thinking that I was going senile, but then I checked and it was William adding that functionality :)

**Comment by pllim** [comment]
Oh ooops! Sorry. I should have checked. I *am* the one getting senile!

**Pull request merged**
