### PR TITLE
Fixes for failures introduced in #702

### PR DESCRIPTION
**Pull request by eteq**
From merging #702 I missed that some of the errors were actually real and not red herrings. This fixes all but one of them, which it should xfail (which I *think* is an upstream issue)

### CODE REVIEW

**Comment by eteq** [comment]
(not that assuming this gets merged I should make a follow-on issue to investigate the one xfail's origin more definitively)

**Comment by dhomeier** [comment]
Looks like the closed-file problem only popped up after adding the `read_fileobj_or_hdulist`, so I second the call for closer investigation.

**Comment by eteq** [comment]
Aww geez, another one popped up in CI here.  I'm going to xfail it for the same reason on the theory that it's only for a few specific input file situations, but definitely needs investigation.

**Comment by dhomeier** [comment]
> Looks like the closed-file problem only popped up after adding the `read_fileobj_or_hdulist` contextmanager, so I second the call for closer investigation.

Rather looks like another red herring; without the changes from #702 merged I am getting the same failures now as well. Seems to be exactly the problem reported in #711; will continue discussion there.

**Pull request merged**
