### PR TITLE
WIP: Display loaders in RTD using sphinx extensions

### LINKED ISSUE #394: Document the default loaders
#376 added several data loaders.  But none of the loaders are actually in the docs.  We need to fix that by adding them to the sphinx docs before a release.

At the same time, the docs on this need some discussion of what the "generic" readers mean.  I.e., that they are intentionally limited because you should write a custom loader instead of using the "generic" readers if you can't do a simple column-to-attribute mapping.

### PR DESCRIPTION
**Pull request by javerbukh**
Using [Sphinx extensions](https://www.sphinx-doc.org/en/master/development/tutorials/helloworld.html), I am displaying the loader formats that are printed out with `Spectrum1D.read.list_formats(out=f)` in read the docs.

Resolves #394

### CODE REVIEW

**Comment by javerbukh** [comment]
Current way loaders are displayed as of the latest commit. Not the prettiest but it's what I could get done this sprint. There are more intricate ways to do this using different kinds of nodes and I will look into that more when I return to this ticket next sprint. 
Screen Shot 2020-04-23 at 1 52 06 PM

**Comment by eteq** [comment]
@javerbukh - is there a reason why something like the *last* paragraph of https://github.com/astropy/specutils/issues/394#issuecomment-613064207 didn't work here?  

That is, instead of having an extension to output this and hard-coding the `txt` file, have the output of ``Spectrum1D.read.list_formats(out=f)`` directly included in the docstrings that are already coming out from ``.. automodapi::`` directives?

My concern as this stands is that it's not very maintainable and seems to be bypassing the built-in sphinx table formatting.

**Comment by javerbukh** [comment]
@eteq My experience with Sphinx is just about this ticket, so I cannot give a great reason for extension over builtin_frames other than I could figure out how extensions work in the given amount of time, lol. I will say that the `.txt` file is not hardcoded, it is simply the only way to get the output of `list_formats` in a usable way. I can come back to this ticket the sprint after next if we cannot merge it as is for the time being.

**Comment by javerbukh** [comment]
There is a better way to perform this task and the PR that is handling that is #675 . Closing this PR.

**Pull request closed without merging**
