### PR TITLE
Fixes problem with non-loadable x1d files

### PR DESCRIPTION
**Pull request by ibusko**
Fixes the bug reported in jdaviz's issue #390. 

The bug was caused by the SRCTYPE keyword being moved around different extensions by different pipeline versions. Or, just not being there. 

Data created by pipeline 0.17.1 mostly works with the fix in here. That is, as long as the keyword is somewhere in the file, it works. Other pipeline versions do not create this keyword (they should, and they will from release B7.7.1, around beginning of March.

Link for 0.17.1 files https://stsci.box.com/s/5rxc5b41p04k8pux91iyn7aij5zhmm1l

### CODE REVIEW

**Comment by ibusko** [comment]
I am adding Brian as an unofficial reviewer.

**Comment by havok2063** [comment]
@ibusko I've tested that this works with 0.17.1 nirspec x1d files that have the correct SRCTYPE keyword in the EXTRACT1D header.  I've also tested the existing 0.17.1 miri mrs x1d files fail due to the missing keyword, but work when I manually add it back in.  I unofficially approve this.  

You may want to add some tests in `tests/test_jwst_reader.py` with a fake HDU to ensure it correctly works and fails with the respective inputs or lack thereof.

**Comment by ibusko** [comment]
> @ibusko I've tested that this works with 0.17.1 nirspec x1d files that have the correct SRCTYPE keyword in the EXTRACT1D header. I've also tested the existing 0.17.1 miri mrs x1d files fail due to the missing keyword, but work when I manually add it back in. I unofficially approve this.
> 
> You may want to add some tests in `tests/test_jwst_reader.py` with a fake HDU to ensure it correctly works and fails with the respective inputs or lack thereof.

There is one already: lines 148-158 in `tests/test_jwst_reader.py`

**Comment by havok2063** [comment]
Ahh true, I didn't see that.

**Review by javerbukh — APPROVED** [review]
Works with 0.17.1 data. Nice fix!

**Review by eteq — APPROVED** [review]
LGTM! Merging.

**Comment by eteq** [comment]
Oh, and the test failure looks to be #773 - we really should fix that since it's possible it's masking other things now... :shrug:

**Pull request merged**
