### PR TITLE
Add common loaders from Data Central

### PR DESCRIPTION
**Pull request by aragilar**
For a bunch of AAT/other Australian surveys (both existing and to be released) we (Data Central) have been using these loaders to reduce duplicate code inside survey-specific loaders. Is this something specutils would be interested in having (I'd include the survey specific ones in a future PR, once we sort out where this code would sit inside specutils)?

### CODE REVIEW

**Comment by aragilar** [comment]
@nmearl @eteq Any comments on this PR? I'd like to start creating PRs for the survey/instrument-specific loaders we've developed, but those PRs require the base loaders in the PR.

**Comment by nmearl** [comment]
In a technical sense, this PR looks great. We would certainly want to move/rename the files to something more specific/descriptive (e.g. `dc_common`/`aat_common`, etc). @eteq thoughts?

**Comment by aragilar** [comment]
I'm happy to rename the file, I figured if I named it `dc_common`, it would be assumed only Data Central created loaders could use it, whereas I though other groups may want to use those loaders as a basis for their surveys/data.

**Comment by aragilar** [comment]
I've done the rename from `common` to `dc_common`.

**Comment by aragilar** [comment]
I've fixed the tests, and added some additional changes we've made to our local copy.

**Comment by nmearl** [comment]
Thanks @aragilar! We should be sure to follow the paradigm of the rest of the code base (e.g. function arguments shouldn't be one-per-line), but it's functionally fine, I think, for loader contributions.

**Comment by aragilar** [comment]
Ah, sorry, I probably ran [black](https://github.com/psf/black) on it at some point, I'll try to remember to change that up before I push other loaders.

**Pull request merged**
