### PR TITLE
Adding tests for basic arith operations.

### LINKED ISSUE #203: Add thorough tests for current arthimetic functions
Once the test infrastructure is setup, we'd like to add a well rounded test set for the +,-,/,* operators with both spectra and constants.  Moved from issue #198

### PR DESCRIPTION
**Pull request by SaOgaz**
Also fixed units in test spectra setup. Closes #203.  Cleaned up some pep8 stuff as well. @brechmos-stsci, not sure who else needs to review this?

### CODE REVIEW

**Comment by SaOgaz** [comment]
Oh, btw, there's a test in test_loaders.py that's marked as xfail but passing for me....

**Comment by bsipocz** [comment]
re: xfail:  Ideally tests are marked xfail when the reason for their fail is known and thus the xfail is limited to the problematic platform, dependency version or use case. 

If you want to be super strict about them, you can use the ``xfail_strict = true`` line in ``setup.cfg`` under the ``pytest`` section and then they'll trigger CI failure when passing. For specutils and especially now when it's in a very rapid development mode, I'm not sure how practical to be that strict.

**Comment by SaOgaz** [comment]
Hmm, @bsipocz the note doesn't say anything about only failing on a specific version:
```
@pytest.mark.xfail(reason='The file L5g_0355+11_Cruz09 does not have a '
                   'spectral axis in its WCS')
```

**Comment by bsipocz** [comment]
Ohh, I remember that one, it was a temporarily measure to make CI green while cleaning up bits and pieces from the previous edition of the package. 
It indeed seems to be working now, so the xfail can be removed.

**Comment by bsipocz** [comment]
I can deal with it while fixing https://github.com/astropy/specutils/issues/213

**Pull request merged**
