### PR TITLE
Feature to load IRAF's equispec spectrum

### PR DESCRIPTION
**Pull request by indiajoe**
This is to load fits equispec spectrum.
IRAF's apall outputs spectrum in this format when it stores extracted sky, variance etc. (the extras=yes flag in apall). 
They are 3 dimensional. The first dimension contains flux, sky value, variance etc. Second dimension contains aperture (typically size 1 if it is not multispec). And third dimension is the dispersion axis.

Ideally, I think we would like to have 2 dimensional flux array to represent this kind of spectrum to avoid repetition of meta data (as I understand from the discussion in #11).

As a temporary and quick solution, this PR creates multiple Spectrum1D for each rows of spectrum (similar to current implementation for multispec format).

For a normal equispec spectrum, it returns a list of Spectrum1D.
For a multispec equispec spectrum, it returns a list of list Spectrum1D.

### CODE REVIEW

**Comment by wkerzendorf** [comment]
hi @indiajoe looks good. Do you want to add your files as a test?

**Comment by indiajoe** [comment]
@wkerzendorf . Sure, shall I put the fits file in specutils/data/ and add the tests in tests/test_spectrum1d.py ?

**Comment by wkerzendorf** [comment]
sounds great!

**Comment by wkerzendorf** [comment]
@indiajoe hi this looks great - sorry it took such a long time to merge.

**Pull request merged**
