### PR TITLE
WIP: Discussion PR on SpectrumCollections decorator

### PR DESCRIPTION
**Pull request by SaOgaz**
Hi all,

@eteq and I had an offline  discussion during my work on the resample code about how we want to work in analysis on spectrum collections. I advocated for a decorator.  I've done an example of what I had in mind here that runs on my resample class.  @eteq had an alternate suggestion that I'm now blanking on.

I like the decorator approach as it seems a little easier to follow for users trying to track what's going on with the code, but this PR is definitely meant for discussion!

### CODE REVIEW

**Comment by nmearl** [comment]
Am I missing it? I don't see a decorator example in the code?

**Comment by SaOgaz** [comment]
@nmearl it would probably help if I included the commit, LOL

**Comment by SaOgaz** [comment]
Oh, another note, @eteq suggested putting the decorator in the SpectrumCollections class as a static method.  I'm not sure I'm convinced of this.  I feel like it makes the decorator call kind of awkward.

**Comment by nmearl** [comment]
Can you provide an example of using this decorator?

**Comment by SaOgaz** [comment]
It's in there.... in the resample function: https://github.com/astropy/specutils/pull/471/files#diff-64489eca25a7793c6b98cd48fa905511R125

**Comment by SaOgaz** [comment]
Feedback from @jkcarlberg, we need to add an example section on usage for these classes, so that when help() is called it shows you how to use.  Otherwise users will (understandably) assume they need to call `resample1D`.

**Comment by pllim** [comment]
This PR is stale and author no longer works at STScI.

**Pull request closed without merging**
